# -*- coding: utf-8 -*-
"""BrainsVersusBrawn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lziVivpU-I5S5GdmI_wRiF5wI64ShgKC
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import mode
import time
from sklearn.decomposition import PCA
import torch.nn.functional as F
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import numpy as np
import seaborn as sns
from sklearn.metrics import roc_curve, auc
import numpy as np
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.model_selection import GridSearchCV, train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
import numpy as np

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

import matplotlib.pyplot as plt
# import kagglehub

# df = kagglehub.dataset_download("maksbasher/ufc-complete-dataset-all-events-1996-2024")

# print("Path to dataset files:", df)
# df.he


# from google.colab import drive
# drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/large_dataset.csv')
df.head()

"""#PREPROCESING DATA"""

weight_class_selection = ['Lightweight', 'UFC Interm Lightweight Title', 'UFC Lightweight Title']
one_weight_class = df[df['weight_class'].isin(weight_class_selection)]
# print(one_weight_class)
fighter_names = one_weight_class[['r_fighter', 'b_fighter']].copy()

one_weight_class.head(4)

# One Hot Encoding is used to convert the categorical data into numeric
#creating a list that holds the cols which are categorical
categorical_cols = df.select_dtypes(include = 'object').columns.tolist()

if 'winner' in categorical_cols:
    categorical_cols.remove('winner')
print(categorical_cols)

one_weight_class.loc[:, categorical_cols] = one_weight_class[categorical_cols].fillna('Unknown')

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoded_data = encoder.fit_transform(one_weight_class[categorical_cols])

# Duplicate fighter names for flipped data too
flipped_fighter_names = fighter_names.copy()
flipped_fighter_names.columns = ['b_fighter', 'r_fighter']  # Swap names
all_fighter_names = pd.concat([fighter_names, flipped_fighter_names], ignore_index=True)

print(all_fighter_names)

#new col names
encoded_cols = list(encoder.get_feature_names_out(categorical_cols))
print(encoded_cols)

# one_weight_class[encoded_cols] = encoder.transform(one_weight_class[categorical_cols])
# encoded_df = pd.DataFrame(encoded_data, columns=encoded_cols, index=one_weight_class.index)

one_weight_class.loc[:,encoded_cols] = encoder.transform(one_weight_class[categorical_cols])
fighter_names = one_weight_class[['r_fighter', 'b_fighter']].copy()
one_weight_class = one_weight_class.drop(columns=categorical_cols)
# one_weight_class
# one_weight_class = pd.concat([one_weight_class, encoded_df], axis=1)
# print(one_weight_class)

# make sure you are augmenting the dataset to flip the order of your fighters in the input features.
"""
 augumentation is a technique used in machine learning to artificially increase the size and diversity of a dataset by creating new, slightly modified versions of existing data.
 This process helps to improve model performance, particularly when dealing with limited or unbalanced datasets, and can also reduce overfitting
"""

def flip_fighter_row(row):
    flipped = row.copy()
    # Swap red and blue fighter features
    for col in row.index:
        if col.startswith('r_'):
            flipped[col] = row.get('b_' + col[2:], np.nan)
        elif col.startswith('b_'):
            flipped[col] = row.get('r_' + col[2:], np.nan)
    # Flip the winner
    if 'winner' in row:
        if row['winner'] == 'Red':
            flipped['winner'] = 'Blue'
        elif row['winner'] == 'Blue':
            flipped['winner'] = 'Red'
        else:
            flipped['winner'] = row['winner']  # For draws/unknown
    return flipped

# Apply flipping to all rows and double the dataset
flipped_df = one_weight_class.apply(flip_fighter_row, axis=1)
augmented_df = pd.concat([one_weight_class, flipped_df], ignore_index=True)

# Attach back to augmented data
fighter_names_df = pd.DataFrame(all_fighter_names, index=augmented_df.index)  # Ensure index alignment
augmented_df = pd.concat([augmented_df, fighter_names_df], axis=1)
augmented_df.head()

# X = one_weight_class.drop(columns=['winner'], errors='ignore')
# y = one_weight_class['winner']
X = augmented_df.drop(columns=['winner'], errors='ignore')
y = augmented_df['winner']
# augmented_df = augmented_df.dropna(subset=['winner'])


# Split the data into training and testing sets
X_trainval, X_test, y_trainval, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Then split train into training and validation
X_train, X_val, y_train, y_val = train_test_split(X_trainval, y_trainval, test_size=0.25, random_state=42)


r_fighter_names = X_trainval['r_fighter']
b_fighter_names = X_trainval['b_fighter']
print(r_fighter_names)
X_train = X_train.drop(columns=['r_fighter', 'b_fighter'])
X_val = X_val.drop(columns=['r_fighter', 'b_fighter']) # Drop for X_val as well
X_test = X_test.drop(columns=['r_fighter', 'b_fighter'])
X_trainval = X_trainval.drop(columns=['r_fighter', 'b_fighter']) # Drop for X_trainval too

#for missing values
imputer = SimpleImputer(strategy='mean')
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#PCA
n_components=15
pca = PCA(n_components=n_components)
X_train = pca.fit_transform(X_train) #Avoiding leakage, only train PCA on training data!
X_test = pca.transform(X_test)       #Transform the testing data based on the training data's PCA fit


# Map components to feature names
loadings = pd.DataFrame(pca.components_.T,
                        columns=[f'PC{i+1}' for i in range(pca.n_components_)],
                        index=X.columns[ : pca.n_features_in_])

top_pc1_features = loadings['PC1'].abs().sort_values(ascending=False).head(3)
print("Top contributing features to PC1:")
print(top_pc1_features)

original_feature_count = X.shape[1]
retained_feature_count = n_components
removed_feature_count = original_feature_count - retained_feature_count

print(f"Original number of features: {original_feature_count}")
print(f"Number of features retained after PCA: {retained_feature_count}")
print(f"Number of features removed: {removed_feature_count}")

feature_contributions = loadings.abs().sum(axis=1)

# Sort and take the features with lowest influence (i.e., least used in PCA)
removed_like_features = feature_contributions.sort_values().head(removed_feature_count)

print("Original features least used by PCA (lowest contribution):")
print(removed_like_features)

"""#Random Forest Classifier"""

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.model_selection import GridSearchCV, train_test_split
import matplotlib.pyplot as plt


# Targets and features
y_winner = augmented_df['winner']

method_cols = [col for col in augmented_df.columns if col.startswith('method_')]
y_method = augmented_df[method_cols].idxmax(axis=1).str.replace('method_', '')
y_round = augmented_df['finish_round']
y_time = augmented_df['time_sec']
X = augmented_df.drop(columns=['winner', 'finish_round', 'time_sec', 'r_fighter', 'b_fighter'] + method_cols)

# Train-test split
X_train, X_test, yw_train, yw_test = train_test_split(X, y_winner, test_size=0.2, random_state=42)
_, _, ym_train, ym_test = train_test_split(X, y_method, test_size=0.2, random_state=42)
_, _, yr_train, yr_test = train_test_split(X, y_round, test_size=0.2, random_state=42)
_, _, yt_train, yt_test = train_test_split(X, y_time, test_size=0.2, random_state=42)

# Winner model (grid search)
param_grid = {'n_estimators': [100, 150, 200, 300]}
grid = GridSearchCV(RandomForestClassifier(random_state=42), param_grid, cv=5, n_jobs=-1)
grid.fit(X_train, yw_train)
winner_model = grid.best_estimator_

# Other models
method_model = RandomForestClassifier(n_estimators=150, random_state=42)
round_model = RandomForestRegressor(n_estimators=150, random_state=42)
time_model = RandomForestRegressor(n_estimators=150, random_state=42)

method_model.fit(X_train, ym_train)
round_model.fit(X_train, yr_train)
time_model.fit(X_train, yt_train)

# Predictions
yw_pred = winner_model.predict(X_test)
ym_pred = method_model.predict(X_test)
yr_pred_raw = round_model.predict(X_test)
yt_pred = time_model.predict(X_test)

# Clamp predicted rounds to actual max round (3 or 5)
original_total_rounds = augmented_df.loc[yw_test.index, 'total_rounds'].values
yr_pred = np.clip(np.round(yr_pred_raw).astype(int), 1, original_total_rounds)

# Evaluation
print("Winner Accuracy:", accuracy_score(yw_test, yw_pred))
print("Method Accuracy:", accuracy_score(ym_test, ym_pred))
print("Round RMSE:", np.sqrt(mean_squared_error(yr_test, yr_pred_raw)))
print("Time RMSE:", np.sqrt(mean_squared_error(yt_test, yt_pred)))

# Helper to format seconds as M:SS
def seconds_to_min_sec(seconds):
    minutes = int(seconds) // 60
    secs = int(seconds) % 60
    return f"{minutes}:{secs:02}"

# Pull fighter names
r_fighters = augmented_df.loc[yw_test.index, 'r_fighter'].values
b_fighters = augmented_df.loc[yw_test.index, 'b_fighter'].values

# Map winner predictions to fighter names
actual_winner_names = [r if w == 'Red' else b for r, b, w in zip(r_fighters, b_fighters, yw_test)]
predicted_winner_names = [r if w == 'Red' else b for r, b, w in zip(r_fighters, b_fighters, yw_pred)]

# Construct results DataFrame
results = pd.DataFrame({
    'Red Fighter': r_fighters,
    'Blue Fighter': b_fighters,

    'Actual Winner': actual_winner_names,
    'Predicted Winner': predicted_winner_names,

    'Actual Method': ym_test.values,
    'Predicted Method': ym_pred,

    'Actual Round': yr_test.round().astype(int).values,
    'Predicted Round': yr_pred,

    'Actual Time': [seconds_to_min_sec(s) for s in yt_test],
    'Predicted Time': [seconds_to_min_sec(s) for s in yt_pred],
})

# Save to CSV
results.to_csv('fight_predictions_comparison.csv', index=False)


import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
import numpy as np

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

import matplotlib.pyplot as plt

# Collect metrics
winner_metrics = {
    "Accuracy": accuracy_score(yw_test, yw_pred),
    "Precision": precision_score(yw_test, yw_pred, pos_label="Red", average='binary'),
    "Recall": recall_score(yw_test, yw_pred, pos_label="Red", average='binary'),
    "F1 Score": f1_score(yw_test, yw_pred, pos_label="Red", average='binary')
}

method_metrics = {
    "Accuracy": accuracy_score(ym_test, ym_pred),
    "Precision": precision_score(ym_test, ym_pred, average='macro', zero_division=0),
    "Recall": recall_score(ym_test, ym_pred, average='macro', zero_division=0),
    "F1 Score": f1_score(ym_test, ym_pred, average='macro', zero_division=0)
}

# Plot bar chart
labels = list(winner_metrics.keys())
x = np.arange(len(labels))
width = 0.35

fig, ax = plt.subplots(figsize=(8, 5))
bar1 = ax.bar(x - width/2, list(winner_metrics.values()), width, label='Winner Model')
bar2 = ax.bar(x + width/2, list(method_metrics.values()), width, label='Method Model')

ax.set_ylabel('Score')
ax.set_title('Random Forest Metrics by Model')
ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.set_ylim(0, 1)
ax.legend()

for rects in [bar1, bar2]:
    for bar in rects:
        height = bar.get_height()
        ax.annotate(f'{height:.2f}',
                    xy=(bar.get_x() + bar.get_width() / 2, height),
                    xytext=(0, 3),
                    textcoords="offset points",
                    ha='center', va='bottom')

plt.tight_layout()
plt.show()


# Recreate predicted values if not already available
yr_pred_raw = round_model.predict(X_test)
yt_pred = time_model.predict(X_test)
original_total_rounds = augmented_df.loc[yw_test.index, 'total_rounds'].values
yr_pred = np.clip(np.round(yr_pred_raw).astype(int), 1, original_total_rounds)

# 1. Confusion Matrix: Winner Prediction
fig1, ax1 = plt.subplots(figsize=(5, 4))
winner_cm = confusion_matrix(yw_test, yw_pred, labels=["Red", "Blue"])
sns.heatmap(winner_cm, annot=True, fmt='d', cmap='Blues', xticklabels=["Red", "Blue"], yticklabels=["Red", "Blue"], ax=ax1)
ax1.set_title("Confusion Matrix: Winner Prediction")
ax1.set_xlabel("Predicted")
ax1.set_ylabel("Actual")
plt.tight_layout()

# 2. Confusion Matrix: Method Prediction
fig2, ax2 = plt.subplots(figsize=(10, 6))
unique_methods = sorted(set(ym_test) | set(ym_pred))
method_cm = confusion_matrix(ym_test, ym_pred, labels=unique_methods)
sns.heatmap(method_cm, annot=True, fmt='d', cmap='Purples', xticklabels=unique_methods, yticklabels=unique_methods, ax=ax2)
ax2.set_title("Confusion Matrix: Method Prediction")
ax2.set_xlabel("Predicted")
ax2.set_ylabel("Actual")
plt.tight_layout()

# 3. Actual vs Predicted Rounds
fig3, ax3 = plt.subplots(figsize=(6, 4))
ax3.scatter(yr_test, yr_pred, alpha=0.5)
ax3.plot([1, 5], [1, 5], 'r--')
ax3.set_title("Actual vs Predicted Rounds")
ax3.set_xlabel("Actual Round")
ax3.set_ylabel("Predicted Round")
plt.tight_layout()

# 4. Actual vs Predicted Time
fig4, ax4 = plt.subplots(figsize=(6, 4))
ax4.scatter(yt_test, yt_pred, alpha=0.5)
max_time = max(max(yt_test), max(yt_pred))
ax4.plot([0, max_time], [0, max_time], 'r--')
ax4.set_title("Actual vs Predicted Time (seconds)")
ax4.set_xlabel("Actual Time")
ax4.set_ylabel("Predicted Time")
plt.tight_layout()

# 5. Residuals: Time Prediction
fig5, ax5 = plt.subplots(figsize=(6, 4))
residuals = yt_test - yt_pred
sns.histplot(residuals, bins=30, kde=True, ax=ax5)
ax5.set_title("Residuals of Finish Time Prediction")
ax5.set_xlabel("Prediction Error (seconds)")
ax5.set_ylabel("Frequency")
plt.tight_layout()

plt.show()


# Collect metrics
winner_metrics = {
    "Accuracy": accuracy_score(yw_test, yw_pred),
    "Precision": precision_score(yw_test, yw_pred, pos_label="Red", average='binary'),
    "Recall": recall_score(yw_test, yw_pred, pos_label="Red", average='binary'),
    "F1 Score": f1_score(yw_test, yw_pred, pos_label="Red", average='binary')
}

method_metrics = {
    "Accuracy": accuracy_score(ym_test, ym_pred),
    "Precision": precision_score(ym_test, ym_pred, average='macro', zero_division=0),
    "Recall": recall_score(ym_test, ym_pred, average='macro', zero_division=0),
    "F1 Score": f1_score(ym_test, ym_pred, average='macro', zero_division=0)
}

# Plot bar chart
labels = list(winner_metrics.keys())
x = np.arange(len(labels))
width = 0.35

fig, ax = plt.subplots(figsize=(8, 5))
bar1 = ax.bar(x - width/2, list(winner_metrics.values()), width, label='Winner Model')
bar2 = ax.bar(x + width/2, list(method_metrics.values()), width, label='Method Model')

ax.set_ylabel('Score')
ax.set_title('Classification Metrics by Model')
ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.set_ylim(0, 1)
ax.legend()

for rects in [bar1, bar2]:
    for bar in rects:
        height = bar.get_height()
        ax.annotate(f'{height:.2f}',
                    xy=(bar.get_x() + bar.get_width() / 2, height),
                    xytext=(0, 3),
                    textcoords="offset points",
                    ha='center', va='bottom')

plt.tight_layout()
plt.show()


def get_fighter_matchups(fighter_name, results_df):
    """
    Given a fighter's name, return all matchups (as Red or Blue corner).
    """
    mask = (results_df['Red Fighter'] == fighter_name) | (results_df['Blue Fighter'] == fighter_name)
    fighter_matches = results_df[mask].copy()

    # Add a column to indicate whether fighter was red or blue
    fighter_matches['Role'] = fighter_matches.apply(
        lambda row: 'Red' if row['Red Fighter'] == fighter_name else 'Blue', axis=1
    )

    # Add a column to indicate outcome for the fighter
    fighter_matches['Did Win'] = fighter_matches.apply(
        lambda row: row['Actual Winner'] == fighter_name, axis=1
    )

    return fighter_matches.reset_index(drop=True)

# Example: lookup all fights involving Rafael Dos Anjos
fighter_name = "Islam Makhachev"
fighter_fights = get_fighter_matchups(fighter_name, results)

print(f"\nAll matchups for {fighter_name}:\n")
print(fighter_fights[['Red Fighter', 'Blue Fighter', 'Role', 'Actual Winner', 'Predicted Winner',
                      'Actual Method', 'Predicted Method', 'Actual Round', 'Predicted Round',
                      'Actual Time', 'Predicted Time', 'Did Win']].to_string(index=False))



def predict_hypothetical_matchup(fighter_red, fighter_blue, full_df, feature_columns,
                                 winner_model, method_model, round_model, time_model, save=False):
    """
    Simulates a matchup between two fighters using the trained models and optionally appends to results.
    """
    # Find past fights
    red_fights = full_df[(full_df['r_fighter'] == fighter_red) | (full_df['b_fighter'] == fighter_red)]
    blue_fights = full_df[(full_df['r_fighter'] == fighter_blue) | (full_df['b_fighter'] == fighter_blue)]

    if red_fights.empty or blue_fights.empty:
        raise ValueError("One or both fighters not found in historical data.")

    # Mean of features
    red_features = red_fights[feature_columns].mean()
    blue_features = blue_fights[feature_columns].mean()
    matchup_features = pd.DataFrame([(red_features + blue_features) / 2]).astype(float)

    # Predictions
    pred_winner_label = winner_model.predict(matchup_features)[0]
    pred_method = method_model.predict(matchup_features)[0]
    pred_round = int(np.clip(np.round(round_model.predict(matchup_features)[0]), 1, 5))
    pred_time_sec = int(time_model.predict(matchup_features)[0])
    pred_time_str = seconds_to_min_sec(pred_time_sec)

    predicted_winner = fighter_red if pred_winner_label == 'Red' else fighter_blue

    print("\n🔥 Hypothetical Matchup Prediction 🔥")
    print(f"Red Fighter: {fighter_red}")
    print(f"Blue Fighter: {fighter_blue}")
    print(f"Predicted Winner: {predicted_winner} ({pred_winner_label} corner)")
    print(f"Predicted Method: {pred_method}")
    print(f"Predicted Round: {pred_round}")
    print(f"Predicted Time: {pred_time_str}")

predict_hypothetical_matchup(
    fighter_red="Dustin Poirier",
    fighter_blue="Charles Oliveira",
    full_df=augmented_df,
    feature_columns=X.columns,
    winner_model=winner_model,
    method_model=method_model,
    round_model=round_model,
    time_model=time_model,
    save=True  # Set to True if you want to save it to CSV
)

# from sklearn.metrics import roc_curve, auc

# # Convert labels to binary (if not already done)
# yw_test_binary = (yw_test == 'Red').astype(int)

# # Predict probabilities for the positive class (Red)
# yw_probs = winner_model.predict_proba(X_test)[:, 1]

# # Compute ROC curve and AUC
# fpr, tpr, _ = roc_curve(yw_test_binary, yw_probs)
# roc_auc = auc(fpr, tpr)

# # Plot ROC Curve
# plt.figure(figsize=(6, 4))
# plt.plot(fpr, tpr, label=f'AUC = {roc_auc:.2f}')
# plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line
# plt.xlabel('False Positive Rate')
# plt.ylabel('True Positive Rate')
# plt.title('ROC Curve - Winner Prediction (Random Forest)')
# plt.legend(loc='lower right')
# plt.grid(True)
# plt.tight_layout()
# plt.show()

"""#DNN Neural Network"""

import pandas as pd
import numpy as np
import tensorflow as tf
import tensorflow.keras as keras
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, mean_squared_error
from sklearn.model_selection import train_test_split

def seconds_to_min_sec(seconds):
    minutes = int(seconds) // 60
    secs = int(seconds) % 60
    return f"{minutes}:{secs:02}"

class WinnerModel(nn.Module):
    def __init__(self, input_dim, hidden_dims=[128, 64, 32, 16, 8, 4]):
        super().__init__()
        self.dropout = nn.Dropout(0.3)
        self.fc1 = nn.Linear(input_dim, hidden_dims[0])
        self.fc2 = nn.Linear(hidden_dims[0], hidden_dims[1])
        self.fc3 = nn.Linear(hidden_dims[1], hidden_dims[2])
        self.fc4 = nn.Linear(hidden_dims[2], hidden_dims[3])
        self.fc5 = nn.Linear(hidden_dims[3], hidden_dims[4])
        self.fc6 = nn.Linear(hidden_dims[4], hidden_dims[5])
        self.output = nn.Linear(hidden_dims[5], 1)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = F.relu(self.fc4(x))
        x = F.relu(self.fc5(x))
        x = F.relu(self.fc6(x))
        # Apply sigmoid to constrain output between 0 and 1
        return torch.sigmoid(self.output(x)) # This line was changed


class MLP(nn.Module):
    def __init__(self, input_dim, output_dim, task='classification', hidden_dims=[128, 64, 32]):
        super().__init__()
        self.dropout = nn.Dropout(0.3)

        self.fc1 = nn.Linear(input_dim, hidden_dims[0])
        self.fc2 = nn.Linear(hidden_dims[0], hidden_dims[1])
        self.fc3 = nn.Linear(hidden_dims[1], hidden_dims[2])
        self.output = nn.Linear(hidden_dims[2], output_dim)
        self.task = task

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        if self.task == 'classification':
            return F.log_softmax(self.output(x), dim=1)
        else:
            return self.output(x)

method_encoder = LabelEncoder()
method_cols = [col for col in augmented_df.columns if col.startswith('method_')]
y_method = augmented_df[method_cols].idxmax(axis=1).str.replace('method_', '')
ym_train = method_encoder.fit_transform(ym_train)
ym_test = method_encoder.transform(ym_test)

y_winner = augmented_df['winner'].map({'Red': 1, 'Blue': 0}).values
y_round = augmented_df['finish_round'].values.astype(float)
y_time = augmented_df['time_sec'].values.astype(float)
X = augmented_df.drop(columns=['winner', 'finish_round', 'time_sec', 'r_fighter', 'b_fighter'] + method_cols)
X = X.replace([np.inf, -np.inf], np.nan)  # Replace infinite values
X = X.fillna(0)


# Train/test splits
# Encode ym_train and ym_test *before* creating tensors
X_train, X_test, yw_train, yw_test = train_test_split(X, y_winner, test_size=0.2, random_state=42)
_, _, ym_train, ym_test = train_test_split(X, y_method, test_size=0.2, random_state=42) #Original line
ym_train = method_encoder.fit_transform(ym_train) # Encode to numerical labels #New line
ym_test = method_encoder.transform(ym_test)      # Encode using the same encoder #New line
_, _, yr_train, yr_test = train_test_split(X, y_round, test_size=0.2, random_state=42)
_, _, yt_train, yt_test = train_test_split(X, y_time, test_size=0.2, random_state=42)

# Tensors
X_train_tensor = torch.tensor(X_train.values, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test.values, dtype=torch.float32)
yw_train_tensor = torch.tensor(yw_train, dtype=torch.float32).view(-1, 1)
yw_test_tensor = torch.tensor(yw_test, dtype=torch.float32).view(-1, 1)
ym_train_tensor = torch.tensor(ym_train, dtype=torch.long)
ym_test_tensor = torch.tensor(ym_test, dtype=torch.long)
yr_train_tensor = torch.tensor(yr_train, dtype=torch.float32).view(-1, 1)
yr_test_tensor = torch.tensor(yr_test, dtype=torch.float32).view(-1, 1)
yt_train_tensor = torch.tensor(yt_train, dtype=torch.float32).view(-1, 1)
yt_test_tensor = torch.tensor(yt_test, dtype=torch.float32).view(-1, 1)

# --- Model Instantiation ---
input_dim = X_train.shape[1]
num_methods = len(method_encoder.classes_)

winner_model = WinnerModel(input_dim)
method_model = MLP(input_dim, num_methods, task='classification')
round_model = MLP(input_dim, 1, task='regression')
time_model = MLP(input_dim, 1, task='regression')

# --- Training Function ---
def train_with_prints(model, X_train, y_train, X_test, y_test, loss_fn, optimizer, epochs=80, name="Model"):
    train_losses = []
    test_losses = []

    for epoch in range(epochs):
        # Training
        model.train()
        optimizer.zero_grad()
        pred_train = model(X_train)
        if isinstance(loss_fn, nn.BCELoss):
            pred_train = pred_train.clamp(min=1e-7, max=1 - 1e-7)
        loss_train = loss_fn(pred_train, y_train)
        loss_train.backward()
        optimizer.step()
        train_losses.append(loss_train.item())

        # Testing
        model.eval()
        with torch.no_grad():
            pred_test = model(X_test)
            if isinstance(loss_fn, nn.BCELoss):
                pred_test = pred_test.clamp(min=1e-7, max=1 - 1e-7)
            loss_test = loss_fn(pred_test, y_test)
            test_losses.append(loss_test.item())

        # Print every 5 epochs
        if (epoch + 1) % 10 == 0 or epoch == 0:
            print(f"[{name}] Epoch [{epoch+1}/{epochs}], Train Loss: {loss_train.item():.4f}, Test Loss: {loss_test.item():.4f}")

    return train_losses, test_losses






# --- Train All Models ---
winner_train_loss, winner_test_loss = train_with_prints(
    winner_model, X_train_tensor, yw_train_tensor,
    X_test_tensor, yw_test_tensor,
    nn.BCELoss(), optim.Adam(winner_model.parameters(), lr=0.0001),
    epochs=80
)

method_train_loss, method_test_loss = train_with_prints(
    method_model, X_train_tensor, ym_train_tensor,
    X_test_tensor, ym_test_tensor,
    nn.NLLLoss(), optim.Adam(method_model.parameters(), lr=0.0001),
    epochs=80
)

round_train_loss, round_test_loss = train_with_prints(
    round_model, X_train_tensor, yr_train_tensor,
    X_test_tensor, yr_test_tensor,
    nn.MSELoss(), optim.Adam(round_model.parameters(), lr=0.0001),
    epochs=80
)

time_train_loss, time_test_loss = train_with_prints(
    time_model, X_train_tensor, yt_train_tensor,
    X_test_tensor, yt_test_tensor,
    nn.MSELoss(), optim.Adam(time_model.parameters(), lr=0.0001),
    epochs=80
)


# --- Evaluation and Output ---
winner_model.eval(); method_model.eval(); round_model.eval(); time_model.eval()

with torch.no_grad():
    yw_pred_labels = (winner_model(X_test_tensor) >= 0.5).int().numpy().flatten()
    ym_pred_labels = torch.argmax(method_model(X_test_tensor), dim=1).numpy()
    yr_pred = torch.clamp(round_model(X_test_tensor), 1, 5).round().int().numpy().flatten()
    yt_pred = time_model(X_test_tensor).numpy().flatten().astype(int)

# --- Build Output DataFrame ---
r_fighters = augmented_df.loc[X_test.index, 'r_fighter'].values
b_fighters = augmented_df.loc[X_test.index, 'b_fighter'].values

actual_winner_names = [r if w == 1 else b for r, b, w in zip(r_fighters, b_fighters, yw_test)]
predicted_winner_names = [r if w == 1 else b for r, b, w in zip(r_fighters, b_fighters, yw_pred_labels)]
actual_methods = method_encoder.inverse_transform(ym_test)
predicted_methods = method_encoder.inverse_transform(ym_pred_labels)

results = pd.DataFrame({
    'Red Fighter': r_fighters,
    'Blue Fighter': b_fighters,
    'Actual Winner': actual_winner_names,
    'Predicted Winner': predicted_winner_names,
    'Actual Method': actual_methods,
    'Predicted Method': predicted_methods,
    'Actual Round': yr_test.astype(int),
    'Predicted Round': yr_pred,
    'Actual Time': [seconds_to_min_sec(s) for s in yt_test],
    'Predicted Time': [seconds_to_min_sec(s) for s in yt_pred],
})

results.to_csv("fight_predictions_dnn_multi.csv", index=False)



def evaluate_classification(y_true, y_pred, labels=None, title="Confusion Matrix"):
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("\nClassification Report:\n", classification_report(y_true, y_pred, target_names=labels, zero_division=0))

    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(6, 4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=labels, yticklabels=labels)
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.title(title)
    plt.tight_layout()
    plt.show()

evaluate_classification(yw_test, yw_pred_labels, labels=["Blue", "Red"], title="Winner Prediction")
evaluate_classification(ym_test, ym_pred_labels, labels=method_encoder.classes_, title="Method Prediction")

winner_train_loss, winner_test_loss = train_with_prints(
    winner_model, X_train_tensor, yw_train_tensor,
    X_test_tensor, yw_test_tensor,
    nn.BCELoss(), optim.Adam(winner_model.parameters(), lr=0.0001), name="WinnerModel"
)

method_train_loss, method_test_loss = train_with_prints(
    method_model, X_train_tensor, ym_train_tensor,
    X_test_tensor, ym_test_tensor,
    nn.NLLLoss(), optim.Adam(method_model.parameters(), lr=0.0001), name="MethodModel"
)

round_train_loss, round_test_loss = train_with_prints(
    round_model, X_train_tensor, yr_train_tensor,
    X_test_tensor, yr_test_tensor,
    nn.MSELoss(), optim.Adam(round_model.parameters(), lr=0.0001), name="RoundModel"
)

time_train_loss, time_test_loss = train_with_prints(
    time_model, X_train_tensor, yt_train_tensor,
    X_test_tensor, yt_test_tensor,
    nn.MSELoss(), optim.Adam(time_model.parameters(), lr=0.0001), name="TimeModel"
)


plt.figure(figsize=(12, 8))

# Winner model
plt.plot(winner_train_loss, label="Winner - Train", linestyle='-')
plt.plot(winner_test_loss, label="Winner - Test", linestyle='--')

# # Method model
# plt.plot(method_train_loss, label="Method - Train", linestyle='-')
# plt.plot(method_test_loss, label="Method - Test", linestyle='--')

# # Round model
# plt.plot(round_train_loss, label="Round - Train", linestyle='-')
# plt.plot(round_test_loss, label="Round - Test", linestyle='--')

# # Time model
# plt.plot(time_train_loss, label="Time - Train", linestyle='-')
# plt.plot(time_test_loss, label="Time - Test", linestyle='--')

plt.title("Training vs Test Loss per Epoch")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()




# --- DNN Metrics ---
winner_metrics_dnn = {
    "Accuracy": accuracy_score(yw_test, yw_pred_labels),
    "Precision": precision_score(yw_test, yw_pred_labels),
    "Recall": recall_score(yw_test, yw_pred_labels),
    "F1 Score": f1_score(yw_test, yw_pred_labels)
}

method_metrics_dnn = {
    "Accuracy": accuracy_score(ym_test, ym_pred_labels),
    "Precision": precision_score(ym_test, ym_pred_labels, average='macro', zero_division=0),
    "Recall": recall_score(ym_test, ym_pred_labels, average='macro', zero_division=0),
    "F1 Score": f1_score(ym_test, ym_pred_labels, average='macro', zero_division=0)
}

# --- Plotting ---
labels = list(winner_metrics_dnn.keys())
x = range(len(labels))
width = 0.35

fig, ax = plt.subplots(figsize=(8, 5))
bar1 = ax.bar([i - width/2 for i in x], list(winner_metrics_dnn.values()), width, label='Winner DNN')
bar2 = ax.bar([i + width/2 for i in x], list(method_metrics_dnn.values()), width, label='Method DNN')

ax.set_ylabel('Score')
ax.set_title('DNN Metrics by Model')
ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.set_ylim(0, 1)
ax.legend()

for bars in [bar1, bar2]:
    for bar in bars:
        height = bar.get_height()
        ax.annotate(f'{height:.2f}', xy=(bar.get_x() + bar.get_width()/2, height),
                    xytext=(0, 3), textcoords="offset points",
                    ha='center', va='bottom')

plt.tight_layout()
plt.show()



def plot_confusion(y_true, y_pred, labels, title):
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=labels, yticklabels=labels)
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.title(title)
    plt.tight_layout()
    plt.show()

plot_confusion(yw_test, yw_pred_labels, ["Blue", "Red"], "Winner Prediction")
plot_confusion(ym_test, ym_pred_labels, method_encoder.classes_, "Method Prediction")


yw_pred_probs = winner_model(X_test_tensor).detach().numpy().flatten()
fpr, tpr, _ = roc_curve(yw_test, yw_pred_probs)
roc_auc = auc(fpr, tpr)

plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
plt.plot([0,1], [0,1], 'k--')
plt.title("ROC Curve (Winner Prediction)")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Round
plt.scatter(yr_test.flatten(), yr_pred, alpha=0.5)
plt.plot([1,5], [1,5], 'r--')
plt.xlabel("Actual Round")
plt.ylabel("Predicted Round")
plt.title("Actual vs Predicted Round")
plt.tight_layout()
plt.show()

# Time
plt.scatter(yt_test.flatten(), yt_pred, alpha=0.5)
plt.plot([0, max(yt_test)], [0, max(yt_test)], 'r--')
plt.xlabel("Actual Time (s)")
plt.ylabel("Predicted Time (s)")
plt.title("Actual vs Predicted Time")
plt.tight_layout()
plt.show()

residuals = yt_test.flatten() - yt_pred
sns.histplot(residuals, bins=30, kde=True)
plt.title("Residuals of Time Prediction")
plt.xlabel("Error (s)")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()





ym_train = method_encoder.fit_transform(ym_train)  # Encode training labels
ym_test = method_encoder.transform(ym_test)
# --- Winner Metrics ---
winner_metrics_dnn = {
    "Accuracy": accuracy_score(yw_test, yw_pred_labels),
    "Precision": precision_score(yw_test, yw_pred_labels, pos_label=1),
    "Recall": recall_score(yw_test, yw_pred_labels, pos_label=1),
    "F1 Score": f1_score(yw_test, yw_pred_labels, pos_label=1)
}

winner_metrics_rf = {
    "Accuracy": accuracy_score(yw_test, (yw_pred == 'Red').astype(int)), # Convert yw_pred to numeric
    "Precision": precision_score(yw_test, (yw_pred == 'Red').astype(int), pos_label=1), # Convert yw_pred to numeric
    "Recall": recall_score(yw_test, (yw_pred == 'Red').astype(int), pos_label=1), # Convert yw_pred to numeric
    "F1 Score": f1_score(yw_test, (yw_pred == 'Red').astype(int), pos_label=1) # Convert yw_pred to numeric
}

# --- Method Metrics ---
method_metrics_dnn = {
    "Accuracy": accuracy_score(ym_test, ym_pred_labels),
    "Precision": precision_score(ym_test, ym_pred_labels, average='macro', zero_division=0),
    "Recall": recall_score(ym_test, ym_pred_labels, average='macro', zero_division=0),
    "F1 Score": f1_score(ym_test, ym_pred_labels, average='macro', zero_division=0)
}

method_metrics_rf = {
    "Accuracy": accuracy_score(ym_test, ym_pred),
    "Precision": precision_score(ym_test, method_encoder.fit_transform(ym_pred), average='macro', zero_division=0), # Transform ym_pred to numeric labels using fit_transform
    "Recall": recall_score(ym_test, method_encoder.fit_transform(ym_pred), average='macro', zero_division=0), # Transform ym_pred to numeric labels using fit_transform
    "F1 Score": f1_score(ym_test, method_encoder.fit_transform(ym_pred), average='macro', zero_division=0) # Transform ym_pred to numeric labels using fit_transform
}

# --- Plotting ---
def plot_metric_comparison(metrics_dnn, metrics_rf, title):
    labels = list(metrics_dnn.keys())
    x = np.arange(len(labels))
    width = 0.35

    fig, ax = plt.subplots(figsize=(8, 5))
    bars1 = ax.bar(x - width/2, list(metrics_dnn.values()), width, label='DNN')
    bars2 = ax.bar(x + width/2, list(metrics_rf.values()), width, label='Random Forest')

    ax.set_ylabel('Score')
    ax.set_title(title)
    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.set_ylim(0, 1)
    ax.legend()

    for bars in [bars1, bars2]:
        for bar in bars:
            height = bar.get_height()
            ax.annotate(f'{height:.2f}',
                        xy=(bar.get_x() + bar.get_width() / 2, height),
                        xytext=(0, 3),
                        textcoords="offset points",
                        ha='center', va='bottom')

    plt.tight_layout()
    plt.show()

plot_metric_comparison(winner_metrics_dnn, winner_metrics_rf, "Winner Classification Metrics: DNN vs Random Forest")
plot_metric_comparison(method_metrics_dnn, method_metrics_rf, "Method Classification Metrics: DNN vs Random Forest")